/**:
  stella_ekf_node:
    ros__parameters:
      odom_frame: 'odom'
      base_link_frame: 'base_link'
      world_frame: 'odom'
      publish_tf: True
      two_d_mode: True
      frequency: 30.0
      odom0: 'stella_slam/camera_pose'
      odom0_config: [True, True, False, False, False, True, True, True, False, False, False, True, False, False, False]
      odom0_differential: False
      odom0_queue_size: 10